name: Docs Publish
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.8'

      - name: Install dependencies (including theme)
        run: |
          python -m pip install --upgrade pip
          pip install -U virtualenv setuptools wheel tox
          sudo apt-get install -y graphviz pandoc
          # Add the theme installation:
          pip install qiskit_sphinx_theme

      - name: Build and publish
        env:
          encrypted_rclone_key: ${{ secrets.encrypted_rclone_key }}
          encrypted_rclone_iv: ${{ secrets.encrypted_rclone_iv }}
        run: |
          tools/deploy_documentation.sh
      - name: Debug installed packages
        run: |
        pip freeze

