name: E2E Tests
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  e2e-tests:
    name: Run e2e tests - ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: ["ubuntu-latest"]
        environment: ["ibm-quantum-production", "ibm-quantum-staging"]
    environment: ${{ matrix.environment }}
    env:
      QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN }}
      QISKIT_IBM_URL: ${{ secrets.QISKIT_IBM_URL }}
      QISKIT_IBM_INSTANCE: ${{ secrets.QISKIT_IBM_INSTANCE }}
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_IN_PARALLEL: True

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt

      - name: Run e2e tests multiple times
        run: |
          for i in {1..20}; do
            echo "Starting e2e test iteration #$i"
            make e2e-test || exit 1
          done