# This code is part of Qiskit.
#
# (C) Copyright IBM 2021.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Integration Tests
on:
  schedule:
    - cron: '0 5 * * *'
  # allow everyone with write access to the repository to trigger the workflow run manually
  workflow_dispatch:
jobs:
  integration-tests-1:
    if: github.repository_owner == 'Qiskit'
    name: Run integration tests 1 - ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      # avoid cancellation of in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        os: [ "ubuntu-latest" ]
        environment: [ "ibm-quantum-production", "ibm-quantum-staging" ]
    environment: ${{ matrix.environment }}
    env:
      QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN }}
      QISKIT_IBM_URL: ${{ secrets.QISKIT_IBM_URL }}
      QISKIT_IBM_INSTANCE: ${{ secrets.QISKIT_IBM_INSTANCE }}
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_IN_PARALLEL: True
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints.txt -e . -r requirements-dev.txt
      - name: Run integration tests 1
        run: make integration-test-1
  integration-tests-2:
    if: github.repository_owner == 'slrrla'
    name: Run integration tests 2 - ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      # avoid cancellation of in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        os: [ "ubuntu-latest" ]
        environment: [ "ibm-quantum-production", "ibm-quantum-staging" ]
    environment: ${{ matrix.environment }}
    env:
      QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN }}
      QISKIT_IBM_URL: ${{ secrets.QISKIT_IBM_URL }}
      QISKIT_IBM_INSTANCE: ${{ secrets.QISKIT_IBM_INSTANCE }}
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_IN_PARALLEL: True
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints.txt -e . -r requirements-dev.txt
      - name: Run integration tests 2
        run: make integration-test-2
  integration-tests-3:
    if: github.repository_owner == 'Qiskit'
    name: Run integration tests 3 - ${{ matrix.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      # avoid cancellation of in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        os: [ "ubuntu-latest" ]
        environment: [ "ibm-quantum-production", "ibm-quantum-staging" ]
    environment: ${{ matrix.environment }}
    env:
      QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN }}
      QISKIT_IBM_URL: ${{ secrets.QISKIT_IBM_URL }}
      QISKIT_IBM_INSTANCE: ${{ secrets.QISKIT_IBM_INSTANCE }}
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_IN_PARALLEL: True
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Run integration tests 3
        run: make integration-test-3