# This code is part of Qiskit.
#
# (C) Copyright IBM 2022.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Unit Tests
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  unit-tests-latest-qiskit-terra:
    if: github.repository_owner == 'slrrla'
    name: Run unit tests with latest code of Qiskit
    runs-on: "ubuntu-latest"
    env:
      LOG_LEVEL: DEBUG
      STREAM_LOG: True
      QISKIT_IN_PARALLEL: True
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all in one go to force pip's resolver to avoid invalid states.
          pip install -c constraints.txt -e . -r requirements-dev.txt git+https://github.com/Qiskit/qiskit.git
      - name: Run tests
        # running unit tests against latest (non-released) code of qiskit-terra gives a basic level
        # of confidence that the integration between qiskit-ibm-provider and qiskit-terra works
        run: make unit-test